server:
    port: 8080
spring:
    application:
        name: api
    config:
        activate:
            on-profile: local
    datasource:
        url: jdbc:mysql://localhost:3306/api?useSSL=false&serverTimezone=Asia/Seoul
        username: root
        password: root_password
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                format_sql: true
